version: "3.9"
services:
  workshop:
    build: .
    volumes:
      - .:/smartcities-workshop/
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "smartcities"
    entrypoint: sh -c 'jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root'